services:
    nginx:
        image: nginx:1.25-alpine
        depends_on:
            - frontend-client
        volumes:
            - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "${NGINX_PORT:-81}:80"
        networks:
            - internal

    frontend-client:
        build: ./frontend/client
        deploy:
            restart_policy:
                condition: on-failure
                delay: 2s
                window: 60s
        networks:
            - internal

networks:
    internal:
