run:
    timeout: 5m
    issues-exit-code: 1
    tests: true

issues:
    exclude-dirs:
        - "vendor"
        - "third_party"
        - "mocks"

linters:
    enable:
        - govet
        - gofumpt
        - staticcheck
        - errcheck
        - unused
        - ineffassign
        - typecheck
        - gofumpt
        - revive

linters-settings:
    errcheck:
        check-type-assertions: true
        check-blank: true

    staticcheck:
        checks: ["all"]

output:
    formats:
        - format: tab
