basePath: /api/v1
definitions:
  controller.AuthCheckHandlerOut:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      surname:
        type: string
    type: object
  controller.AuthLoginHandlerIn:
    properties:
      email:
        maxLength: 150
        type: string
      password:
        maxLength: 150
        type: string
    required:
    - email
    - password
    type: object
  controller.AuthLoginHandlerOut:
    properties:
      auth_user_data:
        $ref: '#/definitions/controller.AuthLoginHandlerOutUserData'
      token:
        type: string
    type: object
  controller.AuthLoginHandlerOutUserData:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      surname:
        type: string
    type: object
  middleware.ErrorJSON:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      error:
        type: string
    type: object
info:
  contact: {}
  description: API документация для auth
  title: Auth API
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.AuthCheckHandlerOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.ErrorJSON'
      security:
      - BearerAuth: []
      summary: Проверить сессию и получить информацию о пользователе
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.AuthLoginHandlerIn'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.AuthLoginHandlerOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.ErrorJSON'
      summary: Аутентификация пользователя
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
