basePath: /api/v1
definitions:
  controller.CreateOrderIn:
    properties:
      details:
        $ref: '#/definitions/controller.CreateOrderInDetails'
      products:
        items:
          $ref: '#/definitions/controller.CreateOrderInProduct'
        minItems: 1
        type: array
    required:
    - details
    - products
    type: object
  controller.CreateOrderInDetails:
    properties:
      client_email:
        type: string
      client_name:
        maxLength: 150
        minLength: 1
        type: string
      client_phone:
        maxLength: 20
        minLength: 1
        type: string
      client_surname:
        maxLength: 150
        minLength: 1
        type: string
      delivery_address:
        maxLength: 150
        minLength: 1
        type: string
    required:
    - client_email
    - client_name
    - client_phone
    - client_surname
    - delivery_address
    type: object
  controller.CreateOrderInProduct:
    properties:
      id:
        minimum: 0
        type: integer
      quantity:
        minimum: 1
        type: integer
    type: object
  controller.CreateOrderOut:
    properties:
      id:
        type: integer
      secret_key:
        type: string
    type: object
  middleware.ErrorJSON:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      error:
        type: string
    type: object
info:
  contact: {}
  description: API документация для orders
  title: Orders API
  version: "1.0"
paths:
  /orders:
    post:
      consumes:
      - application/json
      parameters:
      - description: JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.CreateOrderIn'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.CreateOrderOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.ErrorJSON'
      security:
      - BearerAuth: []
      summary: Создать заказ
      tags:
      - orders
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
