app:
    is_prod: false
    start_timeout: 60
    stop_timeout: 10
    use_fx_logger: true
    use_logger: true

db:
    uri: "postgres://postgres:12345678@localhost:5433/webdev-orders"
    max_attempts: 10
    attempt_sleep_seconds: 3
    migrations_path: "migrations"

http:
    prefix: "api"
    service_name: "orders"
    port: 8082
    stop_timeout: 5
    under_proxy: false
    start_swagger: true

grpc:
    port: 8091

secrets:
    jwt: "T9vq75NyopB05w2iO8Hp4iduv9xHD5woYWgfEDZmpKOOd4CDC8"
